stages:
- build
- test

build:
  stage: build
  script:
  - module unload xalt
  - cc main.c
  - cp a.out $OLCF_DEPLOYMENT_ROOT/hello_world.$CI_BUILD_REF_NAME.exe

test:
  stage: test
  script:
  - module load python/3.5.1
  - module load blocking_qsub
  - python generate_pbs_script.py --account=$BATCH_ACCOUNT --walltime=1800 --num_nodes=4 --deployment_root=$OLCF_DEPLOYMENT_ROOT --num_ranks=64 --executable_filename=hello_world.$CI_BUILD_REF_NAME.exe > $CI_BUILD_REF_NAME.pbs
  - blocking_qsub -v $CI_BUILD_REF_NAME.pbs
